### ISSUE TITLE
Python Front-End To Do List

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#249]
This ticket is meant for collecting missing features, feature requests etc. for the Python front-end (`@Phylanx`). 

- [x] Extracting a single double result from a Phylanx expression invocation should not require `[0]` indexing, generally, return types should be handled dynamically (solved by #251 and #255)
- [x] All symbols generated from `@Phylanx` should have symbol information (#260)
- [x] Allow calling a `@Phylanx` function from within another one
- [x] Add a way to extract the undecorated PhySL expression from the `@Phylanx` decorator (symbol information removed). This is useful for debugging. (#260)
- [x] Support Python lists (convert to `numpy.array()`/`make_vector()`)
- [x] Support Python tuples (convert to `make_list()`)

**Comment by hkaiser** [comment]
@stevenrbrandt, @rtohid: please add more to the list above, if needed

**Comment by stevenrbrandt** [comment]
I've just checked off the boxes because, unless I misunderstand the last two items, all this is done. @hkaiser do you agree?

**Comment by hkaiser** [comment]
yes, thanks!
