### ISSUE TITLE
Alternating Least Square (ALS) Requirements

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#35]
Required primitives:

- [x] Scalar-matrix multiplication
- [x] Matrix transpose
- [x] Matrix multiplication
- [x] Matrix addition / subtraction
- [x] Slicing
- [x] Dot product
- [x] Identity matrix similar to numpy.identity (#146)
- [x] Elementwise comparison similar to numpy (#187)
- [x] Return a matrix with the input vector on its diagonal, similar to `numpy.diag` (#186)

**Comment by hkaiser** [comment]
Could you write a small Python script implementing a naïve version of this algorithm and link it from here, please?

**Comment by hkaiser** [comment]
@rtohid ping?

**Comment by rtohid** [comment]
https://goo.gl/vzRZXx

**Comment by ct-clmsn** [comment]
@scheherzade is this a closed ticket?

**Comment by scheherzade** [comment]
@ct-clmsn Yes, we can close this ticket.
