### ISSUE TITLE
Primitives needed for Keras backend

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#684]
We can start with:
- [x] A max constant similar to `numpy.inf` (see #699)
- [x] NumPy equivalents of:
    - [x] `tanh`
    - [x] `var` (see #706)
    - [x] `std` (see #706)
    - [x] `prod` (see #692)
    - [x] `cumprod` (#758)
    - [x] `clip` (see #731)
    - [x] `reshape` (see #691)
    - [x] `flatten` (see #685)
    - [x] `repeat` (see #726)
    - [x] `tile` (see #694)
    - [x] `dtype.name` (#806, #856)
    - [x] `flip` (see #701)
    - [x] `ndim` (see #730)
    - [x] `zeros`
- [x] Softmax function (Blaze has an implementation, see #688)
- [x] `logsumexp` to compute the log of the sum of exponentials of input elements as in `scipy.misc.logsumexp` (see #734)

**Comment by ct-clmsn** [comment]
@taless474 great idea!

**Comment by ct-clmsn** [comment]
@taless474 not sure if Keras does auto-differentiation but, if it does, would integrating [tangent](https://github.com/google/tangent) be useful?

**Comment by taless474** [comment]
@ct-clmsn Thank you for introducing the tangent. I will study it. For implementing gradients I was looking into [JAX](https://github.com/google/jax).

**Comment by taless474** [comment]
We can also add NumPy equivalents of:
- [ ] `concatenate`
- [ ] `maximum`
- [ ] `minimum`

**Comment by taless474** [comment]
- We need to update:
     - [ ] `all` where it gets `axis` and `keepdims` as arguments.
     - [ ] `transpose` to accept `axes`

- To support CNNs we can add NumPy equivalents of:
    - [ ] `tensordot`
    - [ ] `pad` in its `constant` mode
    - [ ] `flipud` and `fliplr`

- It's good to have Numpy equivalents of:
    - [ ] `insert`
    - [ ] `sign`
    - [ ] `asarray` (I mean a function to convert input array to node_data)

**Comment by ct-clmsn** [comment]
@taless474 would baking in support for the [ONNX](https://onnx.ai/) model format be a reasonable follow up or additional feature? If keras is supported ya'll might be able to load ONNX models built with other toolkits into Phylanx and run them...

**Comment by hkaiser** [comment]
@rtohid would you see a way to implement functionality equivalent to `dtype.name` in the frontend?

**Comment by rtohid** [comment]
@hkaiser It is relatively straightforward if the type of the object is set in the Phylanx scope, for instance:

```py
@Phylanx
def foo():
    a = np.array([1, 2], dtype=float)
    dt = a.dtype.name
```
Not very much so if (1) the type of the object is defined outside of the Phylanx scope or (2) it is set at run-time. I don't think there is any solution for case (2).

**Comment by hkaiser** [comment]
For `dtype.name`: I think we should expose the native `dtype` object for our arrays. Pybind11 supports that directly (see: https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h#L415).

**Comment by stevenrbrandt** [comment]
@taless474 hstack() currently converts both range and list to node data. It does not, however, work for 3d. Does this already cover what you're looking for? If not, what is missing?
```
from phylanx import Phylanx

@Phylanx
def h():
    return hstack([1,2,3])

@Phylanx
def m():
    return hstack([[1,2],[3,4]])

@Phylanx
def t():
    return hstack([
        [[1,2],[3,4]],
        [[5,6],[7,8]],
    ])

@Phylanx
def a():
    return [1,2,3]

@Phylanx
def r():
    return hstack(range(1,4))

print(type(h())) # hstack converts 1d list to an ndarray
print(type(a())) # return a list without conversion
print(type(r())) # hstack converts a range to an ndarray
print(m().shape) # hstack converts a matrix to an ndarray
#print(t().shape) # 3d doesn't work yet
```

**Comment by hkaiser** [comment]
@stevenrbrandt I think this is a problem in the frontend that does not properly handle 3D arrays (lists).

**Comment by taless474** [comment]
@stevenrbrandt thank you for doing this. By `range` I meant the Phylanx ir::range which we usually use as the equivalent of a tuple in python. In:
https://github.com/STEllAR-GROUP/phylanx/blob/master/src/plugins/matrixops/transpose_operation.cpp#L414
I liked the `axes` argument accepts both python list and tuple. I think there should be better ways than what I did in the above code to cover both cases. How do you think we can standardize this and use it for all the primitives that accept different data types as their arguments. Can we have the same thing to convert types in the python side?
I think this is the problem that NumPy did not completely addresseed:
```python
import numpy as np
np.squeeze(10,axis =20)
```
>array(10)
```python
a = np.array(10)
np.squeeze(a,axis =20)
```
>AxisError: axis 20 is out of bounds for array of dimension 0

**Comment by stevenrbrandt** [comment]
@taless474 I've noticed that in PhySL code,
```
cout(hstack(range(1,4)))
```
fails. However,
```
define(v,range(1,4)),
cout(hstack(v))
```
Succeeds. Not quite sure what is going on there, but it looks like you can use a variable to convince hstack() to convert an ir:range to an array.

**Comment by hkaiser** [comment]
@stevenrbrandt this is a bug, please create a ticket about this.

**Comment by hkaiser** [comment]
@taless474 I think we can close this once #856 is merged, would you agree?

**Comment by taless474** [comment]
@hkaiser thank you, I agree.
